# openstack keystone

Openstack:
  Host: 9.9.33.5
  AdminPassword: a0vhHyaRdAAkq2vH76rnMODTQFm6gnh8r0W7Opi6
  ProjectName: sdn_test
  UserName: sdn_test
  UserPassword: sdn123456
  ExternalNetwork: 67658bb0-d138-4371-acce-493cfbfc3800
  ImageId: 67b0efe9-2534-4b33-b9f8-6943e3ed2671
  FlavorId: 7831ac60-5e31-4e8f-9261-2dfc165c6cf4
